# Generated by Django 5.0.1 on 2024-01-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=160)),
                ('image', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('image_files', models.JSONField(verbose_name=models.CharField(max_length=80))),
                ('price', models.IntegerField()),
                ('link', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=160, null=True)),
                ('size', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
            ],
        ),
    ]
