# Generated by Django 5.0.1 on 2024-01-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image_files',
            field=models.JSONField(verbose_name=models.CharField(max_length=600)),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.CharField(max_length=80),
        ),
    ]
