# Generated by Django 5.0.1 on 2024-02-15 18:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
