# Generated by Django 5.0.1 on 2024-01-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_shoe_image_files_alter_shoe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('image_files', models.JSONField(verbose_name=models.CharField(max_length=600))),
                ('price', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('item_type', models.ManyToManyField(to='server.itemtype')),
            ],
        ),
    ]
