# Generated by Django 5.0.1 on 2024-02-22 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='server.itemtype'),
        ),
    ]
