# Generated by Django 5.0.1 on 2024-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_images_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='file_path',
            field=models.CharField(default='', editable=False, max_length=160),
        ),
    ]
