# Generated by Django 5.0.1 on 2024-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_itemtype_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='item_type',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='size',
            field=models.ManyToManyField(to='server.size'),
        ),
    ]
