# Generated by Django 5.0.1 on 2024-02-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_images_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
