# Generated by Django 5.0.1 on 2024-01-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_size_item_type_itemtype_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='size',
            field=models.ManyToManyField(null=True, to='server.size'),
        ),
    ]
