# Generated by Django 5.0.1 on 2024-01-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_itemtype_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='size',
            field=models.ManyToManyField(blank=True, to='server.size'),
        ),
    ]
