# Generated by Django 5.0.1 on 2024-02-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_itemtype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='image_files',
            field=models.JSONField(editable=False, verbose_name=models.CharField(max_length=600)),
        ),
    ]
