# Generated by Django 5.0.1 on 2024-02-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_itemtype_image_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
