# Generated by Django 5.0.1 on 2024-01-31 23:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_itemtype_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
