# Generated by Django 5.0.1 on 2024-02-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_itemtype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
