# Generated by Django 5.0.1 on 2024-02-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_images_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtype',
            name='image_files',
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
