# Generated by Django 5.0.1 on 2024-02-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_blog_options_rename_post_blog_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
