# Generated by Django 5.0.1 on 2024-02-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_remove_itemtype_image_files_alter_images_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='link',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
