# Generated by Django 5.0.1 on 2024-02-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_itemtype_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='link',
            field=models.CharField(max_length=160),
        ),
    ]
