# Generated by Django 5.0.1 on 2024-02-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
