# Generated by Django 5.0.1 on 2024-02-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_howto'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_files',
            field=models.JSONField(blank=True, null=True, verbose_name=models.CharField(max_length=600)),
        ),
    ]
