# Generated by Django 5.0.1 on 2024-02-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_blog_image_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_files',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
