# Generated by Django 5.0.1 on 2024-02-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_remove_blog_image_files_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
